# Generated by Django 6.1 on 2026-09-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_course_student_registration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='aadhaar_last4',
            new_name='aadhaar_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
