# Generated by Django 6.1 on 2026-08-31 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0002_student_course_student_registration_date_and_more'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.TextField(blank=True, help_text='e.g., Pay within 30 days of admission')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission % institute retains', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_account', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'University Accounts',
            },
        ),
        migrations.CreateModel(
            name='UniversityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('payable', 'Payable (Institute owes University)'), ('receivable', 'Receivable (University owes Institute)')], max_length=20)),
                ('fee_type', models.CharField(choices=[('registration', 'Registration Fee'), ('examination', 'Examination Fee'), ('revaluation', 'Revaluation Fee'), ('certificate', 'Certificate Fee'), ('migration', 'Migration Fee'), ('convocation', 'Convocation Fee'), ('processing', 'Student Processing Fee'), ('commission', 'Commission/Revenue Share'), ('refund', 'Refund'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_transactions', to='finance.financeaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_link', to='finance.financetransaction')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_finance_transactions', to='students.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_transactions', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'University Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('cheque', 'Cheque'), ('dd', 'Demand Draft'), ('card', 'Card'), ('payment_gateway', 'Payment Gateway'), ('other', 'Other')], max_length=20)),
                ('voucher_no', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('payable', 'Payable'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financeaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records_created', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financetransaction')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Salaries',
                'ordering': ['-salary_month', '-created_at'],
                'unique_together': {('staff', 'salary_month')},
            },
        ),
    ]
