# Generated by Django 6.1 on 2026-08-31 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('fees', '0001_initial'),
        ('finance', '0002_universityaccount_universitytransaction_staffsalary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('cancellation', 'Course Cancellation'), ('excess_payment', 'Excess Payment'), ('duplicate', 'Duplicate Payment'), ('university_refund', 'University Refund'), ('fee_adjustment', 'Fee Adjustment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('refund_date', models.DateField()),
                ('refund_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('cheque', 'Cheque'), ('dd', 'Demand Draft'), ('card', 'Card'), ('payment_gateway', 'Payment Gateway'), ('other', 'Other')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financeaccount')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='admissions.admission')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_link', to='finance.financetransaction')),
                ('original_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='fees.payment')),
            ],
            options={
                'ordering': ['-refund_date', '-created_at'],
            },
        ),
    ]
