# Generated by Django 6.1 on 2026-08-31 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_branch_expenseentry_branch_financetransaction_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('statement_date', models.DateField(help_text='Bank statement date')),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_deposits', models.DecimalField(decimal_places=2, default=0, help_text='Deposits in transit', max_digits=14)),
                ('unpresented_cheques', models.DecimalField(decimal_places=2, default=0, help_text='Cheques issued but not yet cleared', max_digits=14)),
                ('bank_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reconciled_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled'), ('discrepancy', 'Discrepancy')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='finance.financeaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank Reconciliations',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='GatewaySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('total_collected', models.DecimalField(decimal_places=2, help_text='Total student payments via gateway', max_digits=14)),
                ('gateway_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_on_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_credit_date', models.DateField(blank=True, null=True)),
                ('bank_credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending Settlement'), ('settled', 'Settled'), ('discrepancy', 'Discrepancy')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_settlements', to='finance.financeaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gateway Settlements',
                'ordering': ['-settlement_date'],
            },
        ),
    ]
