# Generated by Django 6.1 on 2026-08-31 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10)),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('gst_type', models.CharField(choices=[('cgst', 'CGST'), ('sgst', 'SGST'), ('igst', 'IGST')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, help_text='GST rate %', max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_type', models.CharField(help_text='income or expense', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'GST Records',
                'ordering': ['-financial_year', '-quarter'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('matched', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_entries', to='finance.financeaccount')),
                ('finance_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financetransaction')),
            ],
            options={
                'verbose_name_plural': 'Bank Statement Entries',
                'ordering': ['-transaction_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('day_not_closed', 'Day Not Closed'), ('expense_pending', 'Expense Pending Approval'), ('refund_pending', 'Refund Pending Approval'), ('salary_pending', 'Salary Pending'), ('low_cash', 'Low Cash Balance'), ('fee_overdue', 'Fee Overdue'), ('university_due', 'University Payment Due'), ('budget_exceeded', 'Budget Exceeded')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_via', models.CharField(blank=True, help_text='email, sms, or notification', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
