# Generated by Django 6.1 on 2026-09-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Incentive amount for counsellor', max_digits=12),
        ),
    ]
