# Generated by Django 6.1 on 2026-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_incentive'),
        ('courses', '0002_course_category'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='admissions.academicsession'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='universities.university'),
        ),
    ]
