# Generated by Django 6.1 on 2026-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_student_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('accountant', 'Accountant')], default='counsellor', max_length=20),
        ),
    ]
