# Generated by Django 6.1 on 2026-08-23 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        ('students', '0002_student_course_student_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='students.student'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
