# Generated by Django 6.1 on 2026-08-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('course_type', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Other', 'Other')], default='UG', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('eligibility', models.TextField(blank=True)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university')),
            ],
            options={
                'ordering': ['university', 'name'],
                'unique_together': {('university', 'code')},
            },
        ),
    ]
