# Generated by Django 6.1 on 2026-08-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Management', 'Management'), ('Computer Applications', 'Computer Applications'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
