# Generated by Django 6.1 on 2026-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_years',
            field=models.PositiveIntegerField(default=3, help_text='Number of years for this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='fee_per_year',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee per year - total fee is auto-calculated', max_digits=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated: fee_per_year × duration_years', max_digits=12),
        ),
    ]
