# Generated by Django 6.1 on 2026-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_years_course_fee_per_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_years',
            field=models.PositiveIntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years')], default=3, help_text='Number of years for this course'),
        ),
    ]
